// <auto-generated />
using System;
using LocationFinder.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocationFinder.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250816221942_FixModelChanges")]
    partial class FixModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocationFinder.API.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BusinessHours")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ZipCode");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            BusinessHours = "Mon-Fri 9AM-5PM",
                            City = "New York",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 40.7505m,
                            Longitude = -73.9934m,
                            Name = "Downtown Office",
                            Phone = "(212) 555-0101",
                            State = "NY",
                            ZipCode = "10001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Rodeo Dr",
                            BusinessHours = "Mon-Sat 10AM-6PM",
                            City = "Beverly Hills",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 34.0901m,
                            Longitude = -118.4065m,
                            Name = "Beverly Hills Branch",
                            Phone = "(310) 555-0202",
                            State = "CA",
                            ZipCode = "90210"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Michigan Ave",
                            BusinessHours = "Mon-Fri 8AM-6PM",
                            City = "Chicago",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 41.8781m,
                            Longitude = -87.6298m,
                            Name = "Chicago Loop Office",
                            Phone = "(312) 555-0303",
                            State = "IL",
                            ZipCode = "60601"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Texas Ave",
                            BusinessHours = "Mon-Fri 9AM-5PM",
                            City = "Houston",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 29.7604m,
                            Longitude = -95.3698m,
                            Name = "Houston Downtown",
                            Phone = "(713) 555-0404",
                            State = "TX",
                            ZipCode = "77001"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Ocean Dr",
                            BusinessHours = "Mon-Sat 9AM-7PM",
                            City = "Miami",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 25.7617m,
                            Longitude = -80.1918m,
                            Name = "Miami Beach Office",
                            Phone = "(305) 555-0505",
                            State = "FL",
                            ZipCode = "33101"
                        },
                        new
                        {
                            Id = 6,
                            Address = "987 Central Ave",
                            BusinessHours = "Mon-Fri 8AM-5PM",
                            City = "Phoenix",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 33.4484m,
                            Longitude = -112.0740m,
                            Name = "Phoenix Central",
                            Phone = "(602) 555-0606",
                            State = "AZ",
                            ZipCode = "85001"
                        },
                        new
                        {
                            Id = 7,
                            Address = "147 Liberty Bell Way",
                            BusinessHours = "Mon-Fri 9AM-5PM",
                            City = "Philadelphia",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 39.9526m,
                            Longitude = -75.1652m,
                            Name = "Philadelphia Historic",
                            Phone = "(215) 555-0707",
                            State = "PA",
                            ZipCode = "19101"
                        },
                        new
                        {
                            Id = 8,
                            Address = "258 Riverwalk Blvd",
                            BusinessHours = "Mon-Sat 10AM-8PM",
                            City = "San Antonio",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 29.4241m,
                            Longitude = -98.4936m,
                            Name = "San Antonio Riverwalk",
                            Phone = "(210) 555-0808",
                            State = "TX",
                            ZipCode = "78201"
                        },
                        new
                        {
                            Id = 9,
                            Address = "369 Harbor Dr",
                            BusinessHours = "Mon-Fri 9AM-6PM",
                            City = "San Diego",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 32.7157m,
                            Longitude = -117.1611m,
                            Name = "San Diego Harbor",
                            Phone = "(619) 555-0909",
                            State = "CA",
                            ZipCode = "92101"
                        },
                        new
                        {
                            Id = 10,
                            Address = "741 Commerce St",
                            BusinessHours = "Mon-Fri 8AM-6PM",
                            City = "Dallas",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Latitude = 32.7767m,
                            Longitude = -96.7970m,
                            Name = "Dallas Downtown",
                            Phone = "(214) 555-1010",
                            State = "TX",
                            ZipCode = "75201"
                        });
                });

            modelBuilder.Entity("LocationFinder.API.Models.ZipCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCodeValue")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("ZipCodeValue")
                        .IsUnique();

                    b.ToTable("ZipCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            Latitude = 40.7505m,
                            Longitude = -73.9934m,
                            State = "NY",
                            ZipCodeValue = "10001"
                        },
                        new
                        {
                            Id = 2,
                            City = "Beverly Hills",
                            Latitude = 34.0901m,
                            Longitude = -118.4065m,
                            State = "CA",
                            ZipCodeValue = "90210"
                        },
                        new
                        {
                            Id = 3,
                            City = "Chicago",
                            Latitude = 41.8781m,
                            Longitude = -87.6298m,
                            State = "IL",
                            ZipCodeValue = "60601"
                        },
                        new
                        {
                            Id = 4,
                            City = "Houston",
                            Latitude = 29.7604m,
                            Longitude = -95.3698m,
                            State = "TX",
                            ZipCodeValue = "77001"
                        },
                        new
                        {
                            Id = 5,
                            City = "Miami",
                            Latitude = 25.7617m,
                            Longitude = -80.1918m,
                            State = "FL",
                            ZipCodeValue = "33101"
                        },
                        new
                        {
                            Id = 6,
                            City = "Phoenix",
                            Latitude = 33.4484m,
                            Longitude = -112.0740m,
                            State = "AZ",
                            ZipCodeValue = "85001"
                        },
                        new
                        {
                            Id = 7,
                            City = "Philadelphia",
                            Latitude = 39.9526m,
                            Longitude = -75.1652m,
                            State = "PA",
                            ZipCodeValue = "19101"
                        },
                        new
                        {
                            Id = 8,
                            City = "San Antonio",
                            Latitude = 29.4241m,
                            Longitude = -98.4936m,
                            State = "TX",
                            ZipCodeValue = "78201"
                        },
                        new
                        {
                            Id = 9,
                            City = "San Diego",
                            Latitude = 32.7157m,
                            Longitude = -117.1611m,
                            State = "CA",
                            ZipCodeValue = "92101"
                        },
                        new
                        {
                            Id = 10,
                            City = "Dallas",
                            Latitude = 32.7767m,
                            Longitude = -96.7970m,
                            State = "TX",
                            ZipCodeValue = "75201"
                        },
                        new
                        {
                            Id = 11,
                            City = "Seattle",
                            Latitude = 47.6062m,
                            Longitude = -122.3321m,
                            State = "WA",
                            ZipCodeValue = "98101"
                        },
                        new
                        {
                            Id = 12,
                            City = "Denver",
                            Latitude = 39.7392m,
                            Longitude = -104.9903m,
                            State = "CO",
                            ZipCodeValue = "80201"
                        },
                        new
                        {
                            Id = 13,
                            City = "Nashville",
                            Latitude = 36.1627m,
                            Longitude = -86.7816m,
                            State = "TN",
                            ZipCodeValue = "37201"
                        },
                        new
                        {
                            Id = 14,
                            City = "New Orleans",
                            Latitude = 29.9511m,
                            Longitude = -90.0715m,
                            State = "LA",
                            ZipCodeValue = "70112"
                        },
                        new
                        {
                            Id = 15,
                            City = "Washington",
                            Latitude = 38.9072m,
                            Longitude = -77.0369m,
                            State = "DC",
                            ZipCodeValue = "20001"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
